import React, { useEffect, useState } from "react";
import {
  Box,
  Kbd,
  Card,
  Flex,
  Text,
  Title,
  Button,
  Container,
} from "@mantine/core";
import { landingCodes, renderCode } from "lib";
import Head from "next/head";
import { Navbar } from "components";

export default function Landing() {
  const [inputValue, setInputValue] = useState<string>("");

  const handleCompleteInput = (code: string) => {
    const nextInputIndex = inputValue.length;
    const nextInputCharacter = code[nextInputIndex];

    setInputValue(inputValue + nextInputCharacter);

    if (nextInputIndex === code.length) {
      setInputValue("");
    }
  };

  useEffect(() => {
    setTimeout(() => handleCompleteInput(landingCodes[0]), 1000);
  }, [inputValue]);

  return (
    <React.Fragment>
      <Head>
        <title>Coders Race</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container bg="#15141a" size="full">
        <Container size="xl" h="100vh" px="xl">
          <Flex justify="space-between" align="center" h="100%">
            <Box w="50%">
              <Title size="h1" fz="4rem" color="#fc5d1b">
                Coders Race
              </Title>
              <Text size="md" fz="1rem" color="#ffffff" fw={500}>
                ¿Qué tan rápido puedes codear?
              </Text>
              <Button variant="primary" mt="md">
                Comenzar
              </Button>
            </Box>
            <Box w="50%">
              <Card pl="xl" bg="#2a2930" radius="lg">
                <pre style={{ fontFamily: "Poppins, sans-serif" }}>
                  {renderCode(landingCodes[0], inputValue)}
                </pre>
              </Card>
            </Box>
          </Flex>
        </Container>
      </Container>
    </React.Fragment>
  );
}

{
  /* <Flex justify="center" w="50%" >
<Textarea
  style={{
    position: "absolute",
    background: "none",
    // fontSize: "100rem",
  }}
  value=""
  onChange={(e) => handleChangeInput(e)}
  w="20rem"
  id="text"
  variant="unstyled"
/>

<pre style={{ fontFamily: "Poppins, sans-serif" }}>
  <span>{handleRenderCode(codeTest, inputValue)}</span>
</pre>
</Flex> */
}
// const useStyles = createStyles(() => ({
//   tab: {
//     fontWeight: 600,
//     color: "#c5c5c6 !important",
//     padding: "0.8rem",
//     "&:hover": {
//       borderTopLeftRadius: "1rem",
//       borderTopRightRadius: "1rem",
//       backgroundColor: "#2a2930",
//     },
//   },
// }));
// // const { classes } = useStyles();
{
  /* <Tabs
      bg="#2a2930"
      color="orange"
      defaultValue="first"
      style={{
        borderTopLeftRadius: "1rem",
        borderTopRightRadius: "1rem",
      }}
      value={"first"}
    >
      <Tabs.List grow>
        <Tabs.Tab value="first" className={classes.tab}>
          JavaScript
        </Tabs.Tab>
        <Tabs.Tab value="second" className={classes.tab}>
          TypeScript
        </Tabs.Tab>
        <Tabs.Tab value="third" className={classes.tab}>
          Phyton
        </Tabs.Tab>
      </Tabs.List>
    </Tabs> */
}
// const handleChangeInput = (e: any) => {
//   const input = e.target.value;
//   const inputLength = inputValue.length;
//   if (codeTest[inputLength] === input) {
//     setInputValue(inputValue + e.target.value);
//   }
// };
