import { mantineThemeProvider } from "styles";
import { MantineProvider } from "@mantine/core";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import Head from "next/head";
import "styles/css/global.css";
import "styles/css/components.css";
import { UserDataProvider } from "../contexts/UserData";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <MantineProvider
      withNormalizeCSS
      withGlobalStyles
      theme={mantineThemeProvider}
    >
      <SessionProvider session={session}>
        <UserDataProvider>
          <Head>
            <title>Coders Race</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Toaster position="bottom-right" />
          <Component {...pageProps} />
        </UserDataProvider>
      </SessionProvider>
    </MantineProvider>
  );
}
