import type { AppProps } from "next/app";
import { mantineThemeProvider } from "styles";
import { MantineProvider } from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import { MobileModal } from "components";
import { Toaster } from "react-hot-toast";
import Head from "next/head";
import "styles/css/global.css";

export default function App({ Component, pageProps }: AppProps) {
  const isMobile = useMediaQuery("(max-width: 768px)");
  console.log(isMobile);

  return (
    <MantineProvider
      withNormalizeCSS
      withGlobalStyles
      theme={mantineThemeProvider}
    >
      <Head>
        <title>Coders Race</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster position="bottom-right" />
      {isMobile ? <MobileModal /> : <Component {...pageProps} />}
    </MantineProvider>
  );
}
