import Head from "next/head";
import { mantineThemeProvider } from "styles";
import { UserDataProvider } from "../contexts/UserData";
import { MantineProvider } from "@mantine/core";
import { SessionProvider } from "next-auth/react";
import { AuthHandler } from "components";
import { NextUIProvider } from "@nextui-org/react";
import { Toaster } from "react-hot-toast";
import "styles/css/global.css";
import "styles/css/components.css";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <NextUIProvider>
      <MantineProvider
        withNormalizeCSS
        withGlobalStyles
        theme={mantineThemeProvider}
      >
        <SessionProvider session={session}>
          <UserDataProvider>
            <Head>
              <title>Coders Race</title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
              />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Toaster position="bottom-right" />
            {Component.auth ? (
              <AuthHandler auth={Component.auth}>
                <Component {...pageProps} />
              </AuthHandler>
            ) : (
              <Component {...pageProps} />
            )}
          </UserDataProvider>
        </SessionProvider>
      </MantineProvider>
    </NextUIProvider>
  );
}
